apiVersion: v1
kind: Pod
metadata:
 name: rainapp
 labels:
  app: rainapp
spec:
  containers:
    - name: rainapp
      image: rainapp:v1
      ports:
        - containerPort: 8080
      ## Parse all value in configmap to env 
      envFrom:
      - configMapRef:
          name: rainapp-config